server.port=${PORT:8083}

# SendGrid settings
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=heenreel@gmail.com

# User JSON Service URL
user.service.url=${USER_SERVICE_URL:http://178.128.218.149:8080}

# Mail service fault tolerance config
mail.user-service.timeout-ms=3000
mail.sendgrid.timeout-ms=5000
mail.queue.capacity=500
mail.queue.poll.delay-ms=2000
mail.executor.core-pool-size=2
mail.executor.max-pool-size=5
